theme: jekyll-theme-hacker
title: Sumit Kumar
description: Engineering teams leader, built systems handling TBs of distributed data, 20x faster ticket resolution, 75% cost savings, 6x faster queries
links:
  resume: ./SumitKumar.pdf
  linkedin: sumit0k
  github: sumit0k
  stackoverflow: 4453633/sumit
  medium: sumit0k
twitter:
  username: sumit0k
  card: summary
logo: ./favicon.ico
social:
  name: Sumit Kumar
  links:
    - https://twitter.com/sumit0k
    - https://www.facebook.com/sumit0kk
    - https://www.instagram.com/sumit0kk
    - https://www.linkedin.com/in/sumit0k
    - https://github.com/sumit0k
    - https://keybase.io/sumitkumar1209
